version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: arp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - arp_network

  backend:
    build: ./backend
    container_name: arp_backend
    restart: always
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=3306
    ports:
      - "5000:5000"
    networks:
      - arp_network

  frontend:
    build: ./frontend
    container_name: arp_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - arp_network

volumes:
  mysql_data:

networks:
  arp_network:
    driver: bridge 